name = "§fNewb Constellation: §9Gemini§r"
version = [0, 1, 0]
min_supported_mc_version = [1, 21, 20]
description = '''
§7Another newb variant that improves Minecraft visual colors, calm tonemap, cozy night skies, and immersive environments.
%v - §c%w§r
''' # %w = patch warning, %v = version
authors = ["firmw4", "devendrn"]
url = "https://devendrn.github.io/newb-shader/"
uuid = "46b3a3db-086f-4a68-8ac5-caf36f49891e" # Use https://www.uuidgenerator.net/version4
materials = ["Sky", "RenderChunk", "Actor", "ActorGlint", "EndSky", "Clouds", "SunMoon", "Weather", "ItemInHandTextured", "ItemInHandColor", "ItemInHandColorGlint", "Stars"]

[info] 
copyright = '''
Copyright © 2024 %a, and "Newb Shader" Contributors

This compiled "Newb Shader" resource pack (source code: https://github.com/devendrn/newb-x-mcbe under MIT License) is licensed under CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/). Redistribute only unmodified copies with proper attribution to "Newb Shader" and variant creators (if any). Do not distribute derivatives.

You can compile the shader from source and distribute the result under your own terms (compatible with the MIT License).

Contact (Discord Server): https://discord.gg/newb-community-844591537430069279
''' # %a = authors
credits = '''
'''

[custom]
label = '''
 - Highly recommended set in-game brightness to 0
 - Low render chunk for better fog experience
 - Don't use experimental features and education mode (or some bugs will occur)
 - Disable Vsync for better performance
 - §4some devices specifically experience a bug in cloud cuttting§r

§7Thanks for downloading and using this shader :)§r
'''
input = '''
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default


[[subpack]]
define = "OPT"
materials = ["Sky", "RenderChunk", "EndSky", "Clouds"]
description = '''
Optimized

Summary:
Rounded cloud, galaxy star, the end blackhole, no wave.
'''

[[subpack]]
define = "BOPT"
materials = ["Sky", "RenderChunk", "EndSky", "Clouds"]
description = '''
Box Optimized

Summary:
Box cloud, galaxy star, the end blackhole, no wave.
'''

[[subpack]]
define = "SOPT"
materials = ["Sky", "RenderChunk", "EndSky", "Clouds"]
description = '''
Soft Optimized

Summary:
Simple cloud, galaxy star, the end blackhole, no wave.
'''

[[subpack]]
define = "MED"
materials = ["Sky", "RenderChunk", "EndSky", "Clouds"]
description = '''
Medium

Summary:
Rounded cloud, twinkling star, no wave.
'''

[[subpack]]
define = "BMED"
materials = ["Sky", "RenderChunk", "EndSky", "Clouds"]
description = '''
Box Medium

Summary:
Box cloud, twinkling star, no wave.
'''

[[subpack]]
define = "SMED"
materials = ["Sky", "RenderChunk", "EndSky", "Clouds"]
description = '''
Soft Medium

Summary:
Simple cloud, twinkling star, no wave.
'''

[[subpack]]
define = "LOW"
materials = ["Sky", "RenderChunk", "EndSky", "Clouds"]
description = '''
Low

Summary:
Box cloud, no wave, no galaxy star, no the end blackhole.
'''

[[subpack]]
define = "LOWEST"
materials = ["Sky", "RenderChunk", "EndSky", "Clouds"]
description = '''
Lowest

Summary:
Simple cloud, no wave, no galaxy star, no the end blackhole.
'''

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
Default

Summary:
Calm tonemap, cozy night skies, galaxy star, the end blackhole and immersive environment.
'''